---
- name: copy job template
  template:
    src: job.nomad
    dest: /tmp/

- name: "Performing '{{ step | default('job') }}' on Nomad server"
  command: nomad run /tmp/job.nomad
  run_once: true

- name: "wait {{ timeout | default(20) }}"
  wait_for:
    timeout: "{{ timeout | default(20) }}"
