---
# We need to determine how many instances are currently running.
- name: Determine how many blue instances are currently running
  shell: "nomad inspect {{ job }} | jq '.Job.TaskGroups[] | select(.Name == \"blue\") | .Count'"
  register: num_instances

- name: Register count_active to {{ num_instances.stdout }}
  set_fact: count_active="{{ num_instances.stdout }}"

- include: blue-green.yml
  vars:
    step: "Bring version {{ version_new }} along existing"
    count_blue:    "{{ count_active }}"
    version_blue:  "{{ version_old }}"
    tags_blue:     "{{ tags_active_with_version_old }}"
    count_green:   "{{ count_active }}"
    version_green: "{{ version_new }}"
    tags_green:    "{{ tags_active_with_version_new }}"

- include: blue-green.yml
  vars:
    step: "Disable old version by using tags"
    count_blue:    "{{ count_active }}"
    version_blue:  "{{ version_old }}"
    tags_blue:     "{{ tags_inactive }}"
    count_green:   "{{ count_active }}"
    version_green: "{{ version_new }}"
    tags_green:    "{{ tags_active_with_version_new }}"

- include: blue-green.yml
  vars:
    step: "Remove old version {{ version_old }} by reducing count to 0"
    count_blue:    0
    version_blue:  "{{ version_old }}"
    tags_blue:     "{{ tags_inactive }}"
    count_green:   "{{ count_active }}"
    version_green: "{{ version_new }}"
    tags_green:    "{{ tags_active_with_version_new }}"

- include: blue-green.yml
  vars:
    step: "enable blue with proper version {{ version_new }} and tags"
    count_blue:    "{{ count_active }}"
    version_blue:  "{{ version_new }}"
    tags_blue:     "{{ tags_active_with_version_new }}"
    count_green:   "{{ count_active }}"
    version_green: "{{ version_new }}"
    tags_green:    "{{ tags_active_with_version_new }}"

- include: blue-green.yml
  vars:
    step: "disable green by using tags"
    count_blue:    "{{ count_active }}"
    version_blue:  "{{ version_new }}"
    tags_blue:     "{{ tags_active_with_version_new }}"
    count_green:   "{{ count_active }}"
    version_green: "{{ version_new }}"
    tags_green:    "{{ tags_inactive }}"

- include: blue-green.yml
  vars:
    step: "remove green by reducing count to 0"
    count_blue:    "{{ count_active }}"
    version_blue:  "{{ version_new }}"
    tags_blue:     "{{ tags_active_with_version_new }}"
    count_green:   0
    version_green: "{{ version_new }}"
    tags_green:    "{{ tags_inactive }}"
