---
# We need to determine how many instances are currently running.
- name: Determine how many blue instances are currently running
  shell: "nomad inspect {{ job }} | jq '.Job.TaskGroups[] | select(.Name == \"blue\") | .Count'"
  register: num_instances

- name: Register count_active to {{ num_instances.stdout }}
  set_fact: count_active="{{ num_instances.stdout }}"
  when: num_instances.rc == 0

- name: new service, default count_active to 0
  set_fact: count_active = 0
  when: num_instances.rc > 0

- include: start-service.yml
  when: count_active|int == 0

- include: perform-blue-green.yml
  when: count_active|int > 0
